type DeepValues<T> = T extends string
  ? T
  : T extends Record<string, unknown>
    ? {
        [K in keyof T]: DeepValues<T[K]>;
      }[keyof T]
    : never;

export const animix = {
  entrance: {
    fade: 'animix-in-fade',
    slideUp: 'animix-in-slide-up',
    slideDown: 'animix-in-slide-down',
    slideLeft: 'animix-in-slide-left',
    slideRight: 'animix-in-slide-right',
    scaleUp: 'animix-in-scale-up',
    scaleDown: 'animix-in-scale-down',
    flipX: 'animix-in-flip-x',
    flipY: 'animix-in-flip-y',
    rotate: 'animix-in-rotate',
    bounce: 'animix-in-bounce',
    elastic: 'animix-in-elastic',
    blur: 'animix-in-blur',
    lightSpeed: 'animix-in-light-speed',
    roll: 'animix-in-roll',
  },
  exit: {
    fade: 'animix-out-fade',
    slideUp: 'animix-out-slide-up',
    slideDown: 'animix-out-slide-down',
    slideLeft: 'animix-out-slide-left',
    slideRight: 'animix-out-slide-right',
    scaleUp: 'animix-out-scale-up',
    scaleDown: 'animix-out-scale-down',
    flipX: 'animix-out-flip-x',
    flipY: 'animix-out-flip-y',
    rotate: 'animix-out-rotate',
    blur: 'animix-out-blur',
    lightSpeed: 'animix-out-light-speed',
    roll: 'animix-out-roll',
    hinge: 'animix-out-hinge',
  },
  attention: {
    pulse: 'animix-pulse',
    bounce: 'animix-bounce',
    shake: 'animix-shake',
    headShake: 'animix-head-shake',
    wiggle: 'animix-wiggle',
    ping: 'animix-ping',
    float: 'animix-float',
    heartbeat: 'animix-heartbeat',
    jello: 'animix-jello',
    rubberBand: 'animix-rubber-band',
    tada: 'animix-tada',
    swing: 'animix-swing',
    wobble: 'animix-wobble',
  },
  transitions: {
    pageFadeIn: 'animix-page-fade-in',
    pageFadeOut: 'animix-page-fade-out',
    pageSlideIn: 'animix-page-slide-in',
    pageSlideOut: 'animix-page-slide-out',
    overlayIn: 'animix-overlay-in',
    overlayOut: 'animix-overlay-out',
    modalIn: 'animix-modal-in',
    modalOut: 'animix-modal-out',
    drawerInRight: 'animix-drawer-in-right',
    drawerOutRight: 'animix-drawer-out-right',
    drawerInLeft: 'animix-drawer-in-left',
    drawerOutLeft: 'animix-drawer-out-left',
    drawerInBottom: 'animix-drawer-in-bottom',
    drawerOutBottom: 'animix-drawer-out-bottom',
    drawerInTop: 'animix-drawer-in-top',
    drawerOutTop: 'animix-drawer-out-top',
    toastInRight: 'animix-toast-in-right',
    toastOutRight: 'animix-toast-out-right',
    toastInBottom: 'animix-toast-in-bottom',
    toastOutBottom: 'animix-toast-out-bottom',
    tooltipIn: 'animix-tooltip-in',
    tooltipOut: 'animix-tooltip-out',
  },
  loaders: {
    spin: 'animix-loader-spin',
    dots: 'animix-loader-dots',
    bars: 'animix-loader-bars',
    pulseRing: 'animix-loader-pulse-ring',
    skeleton: 'animix-loader-skeleton',
    skeletonCircle: 'animix-loader-skeleton-circle',
    typingDots: 'animix-loader-typing-dots',
  },
  modern: {
    scrollRevealUp: 'animix-scroll-reveal-up',
    scrollRevealScale: 'animix-scroll-reveal-scale',
    scrollProgress: 'animix-scroll-progress',
    enterFade: 'animix-enter-fade',
    enterUp: 'animix-enter-up',
    enterScale: 'animix-enter-scale',
    noMotion: 'animix-no-motion',
  },
  utilities: {
    fast: 'animix-fast',
    slow: 'animix-slow',
    slower: 'animix-slower',
    delay0: 'animix-delay-0',
    delay75: 'animix-delay-75',
    delay150: 'animix-delay-150',
    delay300: 'animix-delay-300',
    delay500: 'animix-delay-500',
    delay700: 'animix-delay-700',
    delay1000: 'animix-delay-1000',
    easeDefault: 'animix-ease-default',
    easeIn: 'animix-ease-in',
    easeOut: 'animix-ease-out',
    easeInOut: 'animix-ease-in-out',
    easeSpring: 'animix-ease-spring',
    easeBounce: 'animix-ease-bounce',
    easeLinear: 'animix-ease-linear',
    once: 'animix-once',
    loop: 'animix-loop',
    loop2: 'animix-loop-2',
    loop3: 'animix-loop-3',
    fillBoth: 'animix-fill-both',
    fillForwards: 'animix-fill-forwards',
    fillBackwards: 'animix-fill-backwards',
    fillNone: 'animix-fill-none',
    paused: 'animix-paused',
    running: 'animix-running',
    onHover: 'animix-on-hover',
    onFocus: 'animix-on-focus',
    reverse: 'animix-reverse',
    alternate: 'animix-alt',
    stagger: 'animix-stagger',
    stagger25: 'animix-stagger-25',
    stagger50: 'animix-stagger-50',
    stagger75: 'animix-stagger-75',
    stagger100: 'animix-stagger-100',
    stagger150: 'animix-stagger-150',
  },
  patterns: {
    hoverLift: 'animix-hover-lift',
    pressIn: 'animix-press-in',
    focusSoft: 'animix-focus-soft',
    activePop: 'animix-active-pop',
    iconChevron: 'animix-icon-chevron',
    badgePulseSoft: 'animix-badge-pulse-soft',
    iconSpin: 'animix-icon-spin',
    iconSuccessPop: 'animix-icon-success-pop',
    iconShakeSoft: 'animix-icon-shake-soft',
    iconBellRing: 'animix-icon-bell-ring',
    textHeadlineRise: 'animix-text-headline-rise',
    textStagger: 'animix-text-stagger',
    textUnderlineSweep: 'animix-text-underline-sweep',
    textUnderlineActive: 'animix-text-underline-active',
    counterTick: 'animix-counter-tick',
    imgZoomWrap: 'animix-img-zoom-wrap',
    imgShimmer: 'animix-img-shimmer',
    imgMaskReveal: 'animix-img-mask-reveal',
    imgParallaxLite: 'animix-img-parallax-lite',
    intensityQuiet: 'animix-intensity-quiet',
    originCenter: 'animix-origin-center',
  },
} as const;

export const animateAnimix = {
  entrance: {
    fadeIn: 'animate-animix-fade-in',
    slideUp: 'animate-animix-slide-up',
    slideDown: 'animate-animix-slide-down',
    slideLeft: 'animate-animix-slide-left',
    slideRight: 'animate-animix-slide-right',
    scaleUp: 'animate-animix-scale-up',
    scaleDown: 'animate-animix-scale-down',
    flipX: 'animate-animix-flip-x',
    flipY: 'animate-animix-flip-y',
    rotateIn: 'animate-animix-rotate-in',
    bounceIn: 'animate-animix-bounce-in',
    elasticIn: 'animate-animix-elastic-in',
    blurIn: 'animate-animix-blur-in',
    lightSpeedIn: 'animate-animix-light-speed-in',
    rollIn: 'animate-animix-roll-in',
  },
  exit: {
    fadeOut: 'animate-animix-fade-out',
    slideUpOut: 'animate-animix-slide-up-out',
    slideDownOut: 'animate-animix-slide-down-out',
    slideLeftOut: 'animate-animix-slide-left-out',
    slideRightOut: 'animate-animix-slide-right-out',
    scaleUpOut: 'animate-animix-scale-up-out',
    scaleDownOut: 'animate-animix-scale-down-out',
    flipXOut: 'animate-animix-flip-x-out',
    flipYOut: 'animate-animix-flip-y-out',
    rotateOut: 'animate-animix-rotate-out',
    blurOut: 'animate-animix-blur-out',
    lightSpeedOut: 'animate-animix-light-speed-out',
    rollOut: 'animate-animix-roll-out',
    hingeOut: 'animate-animix-hinge-out',
  },
  attention: {
    pulse: 'animate-animix-pulse',
    bounce: 'animate-animix-bounce-attention',
    shake: 'animate-animix-shake',
    headShake: 'animate-animix-head-shake',
    wiggle: 'animate-animix-wiggle',
    ping: 'animate-animix-ping',
    float: 'animate-animix-float',
    heartbeat: 'animate-animix-heartbeat',
    jello: 'animate-animix-jello',
    rubberBand: 'animate-animix-rubber-band',
    tada: 'animate-animix-tada',
    swing: 'animate-animix-swing',
    wobble: 'animate-animix-wobble',
  },
  transitions: {
    pageFadeIn: 'animate-animix-page-fade-in',
    pageFadeOut: 'animate-animix-page-fade-out',
    pageSlideIn: 'animate-animix-page-slide-in',
    pageSlideOut: 'animate-animix-page-slide-out',
    overlayIn: 'animate-animix-overlay-in',
    overlayOut: 'animate-animix-overlay-out',
    modalIn: 'animate-animix-modal-in',
    modalOut: 'animate-animix-modal-out',
    drawerInRight: 'animate-animix-drawer-in-right',
    drawerOutRight: 'animate-animix-drawer-out-right',
    drawerInLeft: 'animate-animix-drawer-in-left',
    drawerOutLeft: 'animate-animix-drawer-out-left',
    drawerInBottom: 'animate-animix-drawer-in-bottom',
    drawerOutBottom: 'animate-animix-drawer-out-bottom',
    drawerInTop: 'animate-animix-drawer-in-top',
    drawerOutTop: 'animate-animix-drawer-out-top',
    toastIn: 'animate-animix-toast-in',
    toastOut: 'animate-animix-toast-out',
    toastInBottom: 'animate-animix-toast-in-bottom',
    toastOutBottom: 'animate-animix-toast-out-bottom',
    tooltipIn: 'animate-animix-tooltip-in',
    tooltipOut: 'animate-animix-tooltip-out',
  },
  loaders: {
    spin: 'animate-animix-spin',
    skeleton: 'animate-animix-skeleton',
  },
  modern: {
    scrollRevealUp: 'animate-animix-scroll-reveal-up',
    scrollRevealScale: 'animate-animix-scroll-reveal-scale',
    scrollProgress: 'animate-animix-scroll-progress',
    enterFade: 'animate-animix-enter-fade',
    enterUp: 'animate-animix-enter-up',
    enterScale: 'animate-animix-enter-scale',
  },
  patterns: {
    hoverLift: 'animate-animix-hover-lift',
    pressIn: 'animate-animix-press-in',
    focusSoft: 'animate-animix-focus-soft',
    activePop: 'animate-animix-active-pop',
    iconChevron: 'animate-animix-icon-chevron',
    badgePulseSoft: 'animate-animix-badge-pulse-soft',
    iconSpin: 'animate-animix-icon-spin',
    iconSuccessPop: 'animate-animix-icon-success-pop',
    iconShakeSoft: 'animate-animix-icon-shake-soft',
    iconBellRing: 'animate-animix-icon-bell-ring',
    textHeadlineRise: 'animate-animix-text-headline-rise',
    counterTick: 'animate-animix-counter-tick',
    imgMaskReveal: 'animate-animix-img-mask-reveal',
    imgParallaxLite: 'animate-animix-img-parallax-lite',
    imgZoomWrap: 'animate-animix-img-zoom-wrap',
    imgShimmer: 'animate-animix-img-shimmer',
  },
} as const;

export type AnimixClassName = DeepValues<typeof animix>;
export type AnimateAnimixClassName = DeepValues<typeof animateAnimix>;
