export const motionManifest = {
  css: {
    entrance: {
      fade: 'animix-in-fade',
      slideUp: 'animix-in-slide-up',
      slideDown: 'animix-in-slide-down',
      slideLeft: 'animix-in-slide-left',
      slideRight: 'animix-in-slide-right',
      scaleUp: 'animix-in-scale-up',
      scaleDown: 'animix-in-scale-down',
      flipX: 'animix-in-flip-x',
      flipY: 'animix-in-flip-y',
      rotate: 'animix-in-rotate',
      bounce: 'animix-in-bounce',
      elastic: 'animix-in-elastic',
      blur: 'animix-in-blur',
      lightSpeed: 'animix-in-light-speed',
      roll: 'animix-in-roll',
    },
    exit: {
      fade: 'animix-out-fade',
      slideUp: 'animix-out-slide-up',
      slideDown: 'animix-out-slide-down',
      slideLeft: 'animix-out-slide-left',
      slideRight: 'animix-out-slide-right',
      scaleUp: 'animix-out-scale-up',
      scaleDown: 'animix-out-scale-down',
      flipX: 'animix-out-flip-x',
      flipY: 'animix-out-flip-y',
      rotate: 'animix-out-rotate',
      blur: 'animix-out-blur',
      lightSpeed: 'animix-out-light-speed',
      roll: 'animix-out-roll',
      hinge: 'animix-out-hinge',
    },
    attention: {
      pulse: 'animix-pulse',
      bounce: 'animix-bounce',
      shake: 'animix-shake',
      headShake: 'animix-head-shake',
      wiggle: 'animix-wiggle',
      ping: 'animix-ping',
      float: 'animix-float',
      heartbeat: 'animix-heartbeat',
      jello: 'animix-jello',
      rubberBand: 'animix-rubber-band',
      tada: 'animix-tada',
      swing: 'animix-swing',
      wobble: 'animix-wobble',
    },
    transitions: {
      pageFadeIn: 'animix-page-fade-in',
      pageFadeOut: 'animix-page-fade-out',
      pageSlideIn: 'animix-page-slide-in',
      pageSlideOut: 'animix-page-slide-out',
      overlayIn: 'animix-overlay-in',
      overlayOut: 'animix-overlay-out',
      modalIn: 'animix-modal-in',
      modalOut: 'animix-modal-out',
      drawerInRight: 'animix-drawer-in-right',
      drawerOutRight: 'animix-drawer-out-right',
      drawerInLeft: 'animix-drawer-in-left',
      drawerOutLeft: 'animix-drawer-out-left',
      drawerInBottom: 'animix-drawer-in-bottom',
      drawerOutBottom: 'animix-drawer-out-bottom',
      drawerInTop: 'animix-drawer-in-top',
      drawerOutTop: 'animix-drawer-out-top',
      toastInRight: 'animix-toast-in-right',
      toastOutRight: 'animix-toast-out-right',
      toastInBottom: 'animix-toast-in-bottom',
      toastOutBottom: 'animix-toast-out-bottom',
      tooltipIn: 'animix-tooltip-in',
      tooltipOut: 'animix-tooltip-out',
    },
  },
  animate: {
    entrance: {
      fadeIn: 'animate-animix-fade-in',
      slideUp: 'animate-animix-slide-up',
      slideDown: 'animate-animix-slide-down',
      slideLeft: 'animate-animix-slide-left',
      slideRight: 'animate-animix-slide-right',
      scaleUp: 'animate-animix-scale-up',
      scaleDown: 'animate-animix-scale-down',
      flipX: 'animate-animix-flip-x',
      flipY: 'animate-animix-flip-y',
      rotateIn: 'animate-animix-rotate-in',
      bounceIn: 'animate-animix-bounce-in',
      elasticIn: 'animate-animix-elastic-in',
      blurIn: 'animate-animix-blur-in',
      lightSpeedIn: 'animate-animix-light-speed-in',
      rollIn: 'animate-animix-roll-in',
    },
    exit: {
      fadeOut: 'animate-animix-fade-out',
      slideUpOut: 'animate-animix-slide-up-out',
      slideDownOut: 'animate-animix-slide-down-out',
      slideLeftOut: 'animate-animix-slide-left-out',
      slideRightOut: 'animate-animix-slide-right-out',
      scaleUpOut: 'animate-animix-scale-up-out',
      scaleDownOut: 'animate-animix-scale-down-out',
      flipXOut: 'animate-animix-flip-x-out',
      flipYOut: 'animate-animix-flip-y-out',
      rotateOut: 'animate-animix-rotate-out',
      blurOut: 'animate-animix-blur-out',
      lightSpeedOut: 'animate-animix-light-speed-out',
      rollOut: 'animate-animix-roll-out',
      hingeOut: 'animate-animix-hinge-out',
    },
    attention: {
      pulse: 'animate-animix-pulse',
      bounce: 'animate-animix-bounce-attention',
      shake: 'animate-animix-shake',
      headShake: 'animate-animix-head-shake',
      wiggle: 'animate-animix-wiggle',
      ping: 'animate-animix-ping',
      float: 'animate-animix-float',
      heartbeat: 'animate-animix-heartbeat',
      jello: 'animate-animix-jello',
      rubberBand: 'animate-animix-rubber-band',
      tada: 'animate-animix-tada',
      swing: 'animate-animix-swing',
      wobble: 'animate-animix-wobble',
    },
    transitions: {
      pageFadeIn: 'animate-animix-page-fade-in',
      pageFadeOut: 'animate-animix-page-fade-out',
      pageSlideIn: 'animate-animix-page-slide-in',
      pageSlideOut: 'animate-animix-page-slide-out',
      overlayIn: 'animate-animix-overlay-in',
      overlayOut: 'animate-animix-overlay-out',
      modalIn: 'animate-animix-modal-in',
      modalOut: 'animate-animix-modal-out',
      drawerInRight: 'animate-animix-drawer-in-right',
      drawerOutRight: 'animate-animix-drawer-out-right',
      drawerInLeft: 'animate-animix-drawer-in-left',
      drawerOutLeft: 'animate-animix-drawer-out-left',
      drawerInBottom: 'animate-animix-drawer-in-bottom',
      drawerOutBottom: 'animate-animix-drawer-out-bottom',
      drawerInTop: 'animate-animix-drawer-in-top',
      drawerOutTop: 'animate-animix-drawer-out-top',
      toastIn: 'animate-animix-toast-in',
      toastOut: 'animate-animix-toast-out',
      toastInBottom: 'animate-animix-toast-in-bottom',
      toastOutBottom: 'animate-animix-toast-out-bottom',
      tooltipIn: 'animate-animix-tooltip-in',
      tooltipOut: 'animate-animix-tooltip-out',
    },
  },
  react: {
    animation: {
      entrance: {
        fade: 'animix-in-fade',
        'slide-up': 'animix-in-slide-up',
        'slide-down': 'animix-in-slide-down',
        'slide-left': 'animix-in-slide-left',
        'slide-right': 'animix-in-slide-right',
        'scale-up': 'animix-in-scale-up',
        'scale-down': 'animix-in-scale-down',
        'flip-x': 'animix-in-flip-x',
        'flip-y': 'animix-in-flip-y',
        rotate: 'animix-in-rotate',
        bounce: 'animix-in-bounce',
        elastic: 'animix-in-elastic',
        blur: 'animix-in-blur',
        'light-speed': 'animix-in-light-speed',
        roll: 'animix-in-roll',
      },
      exit: {
        fade: 'animix-out-fade',
        'slide-up': 'animix-out-slide-up',
        'slide-down': 'animix-out-slide-down',
        'slide-left': 'animix-out-slide-left',
        'slide-right': 'animix-out-slide-right',
        'scale-up': 'animix-out-scale-up',
        'scale-down': 'animix-out-scale-down',
        'flip-x': 'animix-out-flip-x',
        'flip-y': 'animix-out-flip-y',
        rotate: 'animix-out-rotate',
        blur: 'animix-out-blur',
        'light-speed': 'animix-out-light-speed',
        roll: 'animix-out-roll',
        hinge: 'animix-out-hinge',
      },
      attention: {
        pulse: 'animix-pulse',
        bounce: 'animix-bounce',
        shake: 'animix-shake',
        'head-shake': 'animix-head-shake',
        wiggle: 'animix-wiggle',
        ping: 'animix-ping',
        float: 'animix-float',
        heartbeat: 'animix-heartbeat',
        jello: 'animix-jello',
        'rubber-band': 'animix-rubber-band',
        tada: 'animix-tada',
        swing: 'animix-swing',
        wobble: 'animix-wobble',
      },
      transition: {
        'modal-in': 'animix-modal-in',
        'modal-out': 'animix-modal-out',
        'drawer-in-right': 'animix-drawer-in-right',
        'drawer-out-right': 'animix-drawer-out-right',
        'drawer-in-left': 'animix-drawer-in-left',
        'drawer-out-left': 'animix-drawer-out-left',
        'drawer-in-bottom': 'animix-drawer-in-bottom',
        'drawer-out-bottom': 'animix-drawer-out-bottom',
        'toast-in': 'animix-toast-in-right',
        'toast-out': 'animix-toast-out-right',
        'tooltip-in': 'animix-tooltip-in',
        'tooltip-out': 'animix-tooltip-out',
      },
    },
    intent: {
      button: 'animix-hover-lift animix-focus-soft animix-press-in',
      icon: 'animix-origin-center',
      text: 'animix-intensity-quiet',
      image: 'animix-intensity-quiet animix-origin-center',
    },
  },
  shadcn: {
    animation: {
      scaleUpIn: 'animix-scale-up-in',
      scaleDownOut: 'animix-scale-down-out',
      slideDownIn: 'animix-slide-down-in',
      slideUpIn: 'animix-slide-up-in',
      slideLeftIn: 'animix-slide-left-in',
      slideRightIn: 'animix-slide-right-in',
      accordionDown: 'animix-accordion-down',
      accordionUp: 'animix-accordion-up',
    },
  },
} as const;

export const reactAnimationClassMap = motionManifest.react.animation;
export const reactIntentClassMap = motionManifest.react.intent;
